export interface Topic {
  t: string;
  c: string;
  q: [string, string];
}

export interface TopicCategory {
  label: string;
  icon: string;
}

export const topicCategories: Record<string, TopicCategory> = {
  keluarga: { label: 'Keluarga', icon: 'Home' },
  agama: { label: 'Agama & Ibadah', icon: 'Moon' },
  masa_depan: { label: 'Masa Depan', icon: 'Target' },
  keuangan: { label: 'Keuangan', icon: 'Wallet' },
  karir: { label: 'Karier', icon: 'Briefcase' },
  kesehatan: { label: 'Kesehatan', icon: 'Heart' },
  hobi: { label: 'Hobi & Waktu Luang', icon: 'Sun' },
  sosial: { label: 'Sosial', icon: 'Users' },
  pernikahan: { label: 'Pernikahan', icon: 'HeartHandshake' },
  pendidikan: { label: 'Pendidikan', icon: 'GraduationCap' },
  wisata: { label: 'Wisata', icon: 'Plane' },
  keseharian: { label: 'Keseharian', icon: 'Coffee' },
};

export const taarufTopics: Topic[] = [
  { t: 'Keluarga & orang tua', c: 'keluarga', q: ['Seperti apa sosok orang tuamu?', 'Apa tradisi keluarga yang paling kamu banggakan?'] },
  { t: 'Rumah tangga impian', c: 'masa_depan', q: ['Gambarkan rumah tangga impianmu.', 'Apa suasana yang kamu harapkan di rumah?'] },
  { t: 'Karier & cita-cita', c: 'karir', q: ['Apa cita-cita terbesarmu?', 'Bagaimana rencanamu 5 tahun ke depan?'] },
  { t: 'Ibadah & keistiqomahan', c: 'agama', q: ['Apa ibadah yang paling kamu jaga?', 'Bagaimana caramu menjaga keistiqomahan?'] },
  { t: 'Keuangan keluarga', c: 'keuangan', q: ['Bagaimana kamu mengelola keuangan?', 'Pentingkah transparansi keuangan dalam rumah tangga?'] },
  { t: 'Pendidikan anak', c: 'pendidikan', q: ['Pendidikan seperti apa yang kamu inginkan untuk anak?', 'Bagaimana pandanganmu soal sekolah dan rumah?'] },
  { t: 'Tempat tinggal', c: 'keluarga', q: ['Di mana kamu ingin membangun rumah tangga?', 'Dekat keluarga atau mandiri lebih penting?'] },
  { t: 'Gaya hidup sehat', c: 'kesehatan', q: ['Apa kebiasaan sehat yang kamu jaga?', 'Bagaimana pola makanmu sehari-hari?'] },
  { t: 'Silaturahmi & tetangga', c: 'sosial', q: ['Seberapa penting silaturahmi bagimu?', 'Bagaimana hubunganmu dengan tetangga?'] },
  { t: 'Hobi & waktu luang', c: 'hobi', q: ['Apa hobimu saat ini?', 'Bagaimana kamu mengisi waktu luang?'] },
  { t: 'Pernikahan & peran suami-istri', c: 'pernikahan', q: ['Bagaimana pembagian peran menurutmu?', 'Apa arti pernikahan bagimu?'] },
  { t: 'Doa & harapan', c: 'agama', q: ['Apa doa terbaik yang pernah kamu panjatkan?', 'Apa harapanmu untuk masa depan?'] },
  { t: 'Pengalaman dakwah', c: 'agama', q: ['Apa pengalaman dakwah yang berkesan?', 'Bagaimana caramu berdakwah di lingkunganmu?'] },
  { t: 'Wisata halal', c: 'wisata', q: ['Tempat wisata halal favoritmu?', 'Wisata apa yang ingin kamu coba?'] },
  { t: 'Menghadapi masalah', c: 'keseharian', q: ['Bagaimana caramu menghadapi masalah?', 'Siapa tempatmu curhat saat ada masalah?'] },
  { t: 'Kebiasaan harian', c: 'keseharian', q: ['Bagaimana rutinitas harianmu?', 'Apa kebiasaan kecil yang kamu sukai?'] },
  { t: 'Rencana jangka panjang', c: 'masa_depan', q: ['Apa targetmu 10 tahun ke depan?', 'Bagaimana rencanamu membangun masa depan?'] },
  { t: 'Keluarga besar', c: 'keluarga', q: ['Bagaimana hubunganmu dengan keluarga besar?', 'Seberapa sering kamu berkumpul dengan keluarga besar?'] },
  { t: 'Makanan & masakan rumahan', c: 'hobi', q: ['Apa masakan favoritmu?', 'Kamu bisa masak apa saja?'] },
  { t: 'Teman & lingkungan', c: 'sosial', q: ['Seperti apa lingkaran pertemananmu?', 'Apa yang kamu cari dalam pertemanan?'] },
  { t: 'Cara mengisi waktu luang di akhir pekan', c: 'hobi', q: ['Apa kegiatanmu di akhir pekan?', 'Lebih suka di rumah atau keluar?'] },
  { t: 'Kebiasaan ibadah sunnah yang dijaga', c: 'agama', q: ['Apa sunnah yang kamu rutinkan?', 'Bagaimana caramu konsisten beribadah?'] },
  { t: 'Pengalaman mengaji dan menghafal Al-Quran', c: 'pendidikan', q: ['Bagaimana perjalananmu dengan Al-Quran?', 'Apa target hafalanmu?'] },
  { t: 'Pandangan soal menikah muda', c: 'pernikahan', q: ['Bagaimana pandanganmu soal menikah muda?', 'Apakah kesiapan itu soal usia?'] },
  { t: 'Persiapan sebelum menikah', c: 'pernikahan', q: ['Apa yang kamu siapkan sebelum menikah?', 'Apa yang perlu didiskusikan sebelum menikah?'] },
  { t: 'Kriteria rumah idaman', c: 'masa_depan', q: ['Seperti apa rumah idamanmu?', 'Apartemen atau rumah tapak?'] },
  { t: 'Rencana jumlah anak', c: 'keluarga', q: ['Berapa anak yang kamu idamkan?', 'Jarak usia anak menurutmu?'] },
  { t: 'Peran mertua dalam rumah tangga', c: 'keluarga', q: ['Bagaimana idealnya hubungan dengan mertua?', 'Bagaimana menyikapi campur tangan keluarga?'] },
  { t: 'Cara menyelesaikan konflik', c: 'pernikahan', q: ['Bagaimana caramu menyelesaikan konflik?', 'Apakah kamu mudah marah?'] },
  { t: 'Pentingnya komunikasi dalam keluarga', c: 'pernikahan', q: ['Seberapa penting komunikasi bagimu?', 'Bagaimana gaya komunikasimu?'] },
  { t: 'Tradisi keluarga yang ingin diteruskan', c: 'keluarga', q: ['Apa tradisi yang ingin kamu lestarikan?', 'Apa kebiasaan yang ingin kamu ubah?'] },
  { t: 'Kesibukan sehari-hari', c: 'keseharian', q: ['Apa kesibukanmu sekarang?', 'Bagaimana kamu membagi waktu?'] },
  { t: 'Pengalaman organisasi dan dakwah', c: 'sosial', q: ['Apa pengalaman organisasimu?', 'Apa yang kamu pelajari dari organisasi?'] },
  { t: 'Cara mengelola stres', c: 'kesehatan', q: ['Bagaimana caramu mengelola stres?', 'Apa yang membuatmu tenang?'] },
  { t: 'Pola makan dan kesehatan', c: 'kesehatan', q: ['Bagaimana pola makanmu?', 'Apa upayamu menjaga kesehatan?'] },
  { t: 'Olahraga yang disukai', c: 'kesehatan', q: ['Apa olahraga favoritmu?', 'Seberapa rutin kamu berolahraga?'] },
  { t: 'Buku favorit dan alasannya', c: 'pendidikan', q: ['Apa buku favoritmu?', 'Apa pelajaran dari buku itu?'] },
  { t: 'Film atau tontonan yang bermanfaat', c: 'hobi', q: ['Apa tontonan favoritmu?', 'Bagaimana kamu memilih tontonan?'] },
  { t: 'Pengalaman traveling terbaik', c: 'wisata', q: ['Apa pengalaman traveling terbaikmu?', 'Destinasi apa yang paling berkesan?'] },
  { t: 'Kota yang ingin dikunjungi', c: 'wisata', q: ['Kota apa yang ingin kamu kunjungi?', 'Kenapa kota itu?'] },
  { t: 'Cita-cita yang belum tercapai', c: 'masa_depan', q: ['Apa cita-cita yang belum tercapai?', 'Apa rencanamu untuk mewujudkannya?'] },
  { t: 'Pencapaian yang paling dibanggakan', c: 'karir', q: ['Apa pencapaian yang paling kamu banggakan?', 'Apa yang membuatmu bangga pada dirimu?'] },
  { t: 'Kesalahan yang pernah diperbaiki', c: 'keseharian', q: ['Apa kesalahan yang pernah kamu perbaiki?', 'Apa pelajaran berharga darinya?'] },
  { t: 'Sifat diri yang sedang diperbaiki', c: 'keseharian', q: ['Sifat apa yang sedang kamu perbaiki?', 'Bagaimana caramu memperbaikinya?'] },
  { t: 'Orang yang paling berpengaruh dalam hidup', c: 'keluarga', q: ['Siapa orang yang paling berpengaruh?', 'Apa yang kamu pelajari darinya?'] },
  { t: 'Teladan dalam berumah tangga', c: 'pernikahan', q: ['Siapa teladan rumah tanggamu?', 'Apa yang kamu kagumi dari mereka?'] },
  { t: 'Pandangan soal karir istri/suami bekerja', c: 'karir', q: ['Bagaimana pandanganmu soal dua-duanya bekerja?', 'Bagaimana pembagian tanggung jawabnya?'] },
  { t: 'Kesepakatan soal keuangan bersama', c: 'keuangan', q: ['Bagaimana idealnya keuangan keluarga dikelola?', 'Siapa yang memegang keuangan?'] },
  { t: 'Tabungan dan investasi', c: 'keuangan', q: ['Apa pandanganmu soal menabung?', 'Investasi apa yang kamu minati?'] },
  { t: 'Pandangan soal utang dan gaya hidup', c: 'keuangan', q: ['Bagaimana pandanganmu soal utang?', 'Seberapa penting gaya hidup sederhana?'] },
  { t: 'Zakat, infaq, sedekah', c: 'agama', q: ['Bagaimana kebiasaan sedekahmu?', 'Apa pandanganmu soal zakat?'] },
  { t: 'Menjaga silaturahmi saat sibuk', c: 'sosial', q: ['Bagaimana caramu menjaga silaturahmi?', 'Apa tantangan menjaga silaturahmi?'] },
  { t: 'Rencana berkunjung ke keluarga besar', c: 'keluarga', q: ['Seberapa sering kamu pulang ke keluarga?', 'Apa rencanamu berkumpul keluarga?'] },
  { t: 'Tahun-tahun pertama pernikahan', c: 'pernikahan', q: ['Apa tantangan tahun pertama pernikahan?', 'Bagaimana mempersiapkannya?'] },
  { t: 'Pembagian tugas rumah tangga', c: 'pernikahan', q: ['Bagaimana pembagian tugas yang ideal?', 'Apa tugas yang kamu siap ambil?'] },
  { t: 'Kebiasaan yang harus dikorbankan setelah menikah', c: 'pernikahan', q: ['Apa yang rela kamu korbankan?', 'Apa yang sulit kamu lepaskan?'] },
  { t: 'Hal paling penting dalam pernikahan', c: 'pernikahan', q: ['Apa yang paling penting dalam pernikahan?', 'Apa yang membuat pernikahan bertahan?'] },
  { t: 'Cara menyampaikan pendapat dengan santun', c: 'pernikahan', q: ['Bagaimana caramu menyampaikan pendapat?', 'Bagaimana menyikapi perbedaan pendapat?'] },
  { t: 'Mengelola perbedaan pendapat', c: 'pernikahan', q: ['Bagaimana menyelesaikan beda pendapat?', 'Apa batasan yang perlu disepakati?'] },
  { t: 'Pentingnya waktu berkualitas berdua', c: 'pernikahan', q: ['Apa arti quality time bagimu?', 'Apa kegiatan yang ingin dilakukan berdua?'] },
  { t: 'Rencana liburan keluarga', c: 'wisata', q: ['Apa rencana liburan keluargamu?', 'Liburan seperti apa yang kamu idamkan?'] },
  { t: 'Pendidikan anak di rumah', c: 'pendidikan', q: ['Apa yang ingin kamu ajarkan di rumah?', 'Bagaimana pembentukan karakter anak?'] },
  { t: 'Pemilihan sekolah anak', c: 'pendidikan', q: ['Sekolah seperti apa untuk anakmu?', 'Apa pertimbangan memilih sekolah?'] },
  { t: 'Menjaga kesehatan keluarga', c: 'kesehatan', q: ['Bagaimana menjaga kesehatan keluarga?', 'Apa kebiasaan sehat yang ditularkan?'] },
  { t: 'Rencana pensiun dan masa tua', c: 'masa_depan', q: ['Bagaimana rencanamu masa tua?', 'Apa impianmu setelah pensiun?'] },
  { t: 'Pengalaman membantu orang lain', c: 'sosial', q: ['Apa pengalamanmu membantu orang lain?', 'Bagaimana perasaanmu setelah membantu?'] },
  { t: 'Kegiatan sosial yang pernah diikuti', c: 'sosial', q: ['Apa kegiatan sosial favoritmu?', 'Apa yang kamu pelajari dari kegiatan sosial?'] },
  { t: 'Harapan untuk anak-anak di masa depan', c: 'keluarga', q: ['Apa harapanmu untuk anak-anak?', 'Nilai apa yang ingin kamu tanamkan?'] },
  { t: 'Doa dan harapan untuk pernikahan', c: 'pernikahan', q: ['Apa doamu untuk pernikahan nanti?', 'Apa harapan terbesarmu?'] },
  { t: 'Apa arti rumah tangga bahagia menurutmu', c: 'masa_depan', q: ['Apa definisi bahagia bagimu?', 'Apa yang membuat rumah tangga terasa nyaman?'] },
];

export const pertanyaanStages = [
  { name: 'Perkenalan', questions: ['Ceritakan sedikit tentang dirimu dan keluargamu.', 'Apa kegiatanmu sehari-hari di luar kerja/kuliah?', 'Apa yang paling kamu syukuri akhir-akhir ini?'] },
  { name: 'Agama & Ibadah', questions: ['Bagaimana kebiasaan ibadahmu sehari-hari?', 'Apa yang kamu lakukan untuk menjaga keistiqomahan?', 'Bagaimana pandanganmu soal menuntut ilmu agama?'] },
  { name: 'Keluarga', questions: ['Bagaimana hubunganmu dengan orang tua dan saudara?', 'Apa harapanmu soal hubungan dengan keluarga besar?', 'Bagaimana cara keluargamu mengambil keputusan penting?'] },
  { name: 'Masa Depan', questions: ['Gambarkan rumah tangga impianmu 5-10 tahun ke depan.', 'Bagaimana pembagian peran dalam rumah tangga menurutmu?', 'Apa rencanamu soal pendidikan anak nanti?'] },
  { name: 'Finansial & Karir', questions: ['Bagaimana cara kamu mengelola keuangan?', 'Apa target karirmu dalam 5 tahun ke depan?', 'Bagaimana pandanganmu soal keuangan keluarga?'] },
];

export const iniituDeck = [
  { a: 'Kota kecil yang tenang', b: 'Kota besar yang ramai' },
  { a: 'Masak sendiri di rumah', b: 'Makan di luar' },
  { a: 'Bangun pagi', b: 'Begadang' },
  { a: 'Liburan ke gunung', b: 'Liburan ke pantai' },
  { a: 'Hemat & menabung', b: 'Nikmati hasil kerja' },
  { a: 'Ngobrol langsung', b: 'Chatting' },
  { a: 'Kumpul keluarga besar', b: 'Quality time berdua' },
  { a: 'Rutinitas terjadwal', b: 'Spontan' },
  { a: 'Teh hangat', b: 'Kopi' },
  { a: 'Sarapan di rumah', b: 'Sarapan di luar' },
  { a: 'Membaca buku', b: 'Menonton film' },
  { a: 'Rumah bertingkat', b: 'Rumah satu lantai' },
  { a: 'Menabung dulu baru beli', b: 'Cicil barang impian' },
  { a: 'Dekat tempat kerja', b: 'Dekat keluarga' },
  { a: 'Hujan', b: 'Panas terik' },
  { a: 'Diam saat lelah', b: 'Bercerita saat lelah' },
  { a: 'Berbagi tugas rumah', b: 'Satu orang pegang penuh' },
  { a: 'Undangan keluarga sederhana', b: 'Acara meriah' },
  { a: 'Kado untuk orang tua', b: 'Kado untuk pasangan' },
  { a: 'Merayakan momen kecil', b: 'Hanya momen besar' },
];
